In [6]:
import numpy as np

In [8]:
import numpy as np

consumo = np.array([
    [12.5, 13.2, 11.9, 14.0, 13.5, 15.0, 14.3],
    [10.1, 10.5, 10.0, 11.2, 11.5, 12.0, 11.8],
    [14.0, 14.2, 13.9, 15.5, 15.1, 16.0, 15.8],
    [9.0, 9.2, 8.9, 9.5, 9.8, 10.0, 9.7],
    [16.2, 16.5, 16.0, 17.1, 17.4, 18.0, 17.8],
    [11.0, 11.3, 11.1, 12.0, 12.4, 12.8, 12.5],
    [13.5, 13.8, 13.2, 14.1, 14.6, 15.0, 14.9],
    [10.8, 11.0, 10.6, 11.5, 11.8, 12.2, 12.0],
    [15.1, 15.5, 15.0, 16.0, 16.4, 17.0, 16.7],
    [8.5, 8.7, 8.4, 9.0, 9.2, 9.5, 9.3]
])


hogar5viernes = consumo[4, 4]
print('consumo hogar 5 viernes')
print(hogar5_viernes)


ultimos3domingo = consumo[-3:, 6]
print('consumo ultimos 3 hogares domingo')
print(ultimos3domingo)


finsemana = consumo[:, 5:7]
promediofin = np.mean(finsemana)
print('promedio fin de semana')
print(promediofin)


desviacion = np.std(consumo, axis=0)
diamayor = np.argmax(desviacion)
print('desviacion por dia')
print(desviacion)
print('dia mayor desviacion')
print(dia_mayor)


totalhogar = np.sum(consumo, axis=1)
indicesmenores = np.argsort(totalhogar)[:3]
valoresmenores = totalhogar[indicesmenores]

print('hogares con menor consumo')
print(indicesmenores)
print('valores')
print(valoresmenores)


hogar3 = consumo[2]
aumento = hogar3 * 1.10
nuevototal = np.sum(aumento)

print('nuevo consumo hogar 3')
print(nuevototal)

consumo hogar 5 viernes
17.4
consumo ultimos 3 hogares domingo
[12.  16.7  9.3]
promedio fin de semana
13.615
desviacion por dia
[2.46983805 2.50936247 2.43515913 2.62695641 2.58032944 2.74417565
 2.73561693]
dia mayor desviacion
5
hogares con menor consumo
[9 3 1]
valores
[62.6 66.1 77.1]
nuevo consumo hogar 3
114.94999999999999
